### ISSUE TITLE
bdist_rpm broken with declarative config

### ISSUE THREAD

**Issue by itsadok** [jaraco/configparser#37]
It seems that setuptools can't handle non-ascii setup.cfg. If I delete the author from setup.cfg it works fine.

```
$ python setup.py bdist_rpm
running bdist_rpm
running egg_info
writing src/configparser.egg-info/PKG-INFO
writing dependency_links to src/configparser.egg-info/dependency_links.txt
writing requirements to src/configparser.egg-info/requires.txt
writing top-level names to src/configparser.egg-info/top_level.txt
reading manifest file 'src/configparser.egg-info/SOURCES.txt'
writing manifest file 'src/configparser.egg-info/SOURCES.txt'
writing 'build/bdist.linux-x86_64/rpm/SPECS/configparser.spec'
running sdist
running check
creating configparser-3.7.4
creating configparser-3.7.4/src
creating configparser-3.7.4/src/backports
creating configparser-3.7.4/src/backports/configparser
creating configparser-3.7.4/src/configparser.egg-info
copying files to configparser-3.7.4...
copying LICENSE -> configparser-3.7.4
copying README.rst -> configparser-3.7.4
copying setup.cfg -> configparser-3.7.4
copying setup.py -> configparser-3.7.4
copying src/configparser.py -> configparser-3.7.4/src
copying src/backports/__init__.py -> configparser-3.7.4/src/backports
copying src/backports/configparser/__init__.py -> configparser-3.7.4/src/backports/configparser
copying src/backports/configparser/helpers.py -> configparser-3.7.4/src/backports/configparser
copying src/configparser.egg-info/PKG-INFO -> configparser-3.7.4/src/configparser.egg-info
copying src/configparser.egg-info/SOURCES.txt -> configparser-3.7.4/src/configparser.egg-info
copying src/configparser.egg-info/dependency_links.txt -> configparser-3.7.4/src/configparser.egg-info
copying src/configparser.egg-info/requires.txt -> configparser-3.7.4/src/configparser.egg-info
copying src/configparser.egg-info/top_level.txt -> configparser-3.7.4/src/configparser.egg-info
Writing configparser-3.7.4/setup.cfg
Creating tar archive
removing 'configparser-3.7.4' (and everything under it)
copying dist/configparser-3.7.4.tar.gz -> build/bdist.linux-x86_64/rpm/SOURCES
building RPMs
sh: 1: editable: not found
sh: 1: string-like: not found
rpmbuild -ba --define __python python3 --define _topdir /tmp/configparser/build/bdist.linux-x86_64/rpm --clean build/bdist.linux-x86_64/rpm/SPECS/configparser.spec
sh: 1: editable: not found
sh: 1: string-like: not found
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.X7ocP0
+ umask 022
+ cd /tmp/configparser/build/bdist.linux-x86_64/rpm/BUILD
+ cd /tmp/configparser/build/bdist.linux-x86_64/rpm/BUILD
+ rm -rf configparser-3.7.4
+ /bin/gzip -dc /tmp/configparser/build/bdist.linux-x86_64/rpm/SOURCES/configparser-3.7.4.tar.gz
+ /bin/tar -xvvof -
drwxr-xr-x israel.tsadok/dev 0 2019-03-26 10:16 configparser-3.7.4/
-rw-r--r-- israel.tsadok/dev 9992 2019-03-26 10:05 configparser-3.7.4/README.rst
drwxr-xr-x israel.tsadok/dev    0 2019-03-26 10:16 configparser-3.7.4/src/
drwxr-xr-x israel.tsadok/dev    0 2019-03-26 10:16 configparser-3.7.4/src/backports/
drwxr-xr-x israel.tsadok/dev    0 2019-03-26 10:16 configparser-3.7.4/src/backports/configparser/
-rw-r--r-- israel.tsadok/dev 7648 2019-03-26 10:05 configparser-3.7.4/src/backports/configparser/helpers.py
-rw-r--r-- israel.tsadok/dev 55398 2019-03-26 10:05 configparser-3.7.4/src/backports/configparser/__init__.py
-rw-r--r-- israel.tsadok/dev   211 2019-03-26 10:05 configparser-3.7.4/src/backports/__init__.py
-rw-r--r-- israel.tsadok/dev  1560 2019-03-26 10:05 configparser-3.7.4/src/configparser.py
drwxr-xr-x israel.tsadok/dev     0 2019-03-26 10:16 configparser-3.7.4/src/configparser.egg-info/
-rw-r--r-- israel.tsadok/dev    23 2019-03-26 10:16 configparser-3.7.4/src/configparser.egg-info/top_level.txt
-rw-r--r-- israel.tsadok/dev   120 2019-03-26 10:16 configparser-3.7.4/src/configparser.egg-info/requires.txt
-rw-r--r-- israel.tsadok/dev     1 2019-03-26 10:16 configparser-3.7.4/src/configparser.egg-info/dependency_links.txt
-rw-r--r-- israel.tsadok/dev 12559 2019-03-26 10:16 configparser-3.7.4/src/configparser.egg-info/PKG-INFO
-rw-r--r-- israel.tsadok/dev   359 2019-03-26 10:16 configparser-3.7.4/src/configparser.egg-info/SOURCES.txt
-rw-r--r-- israel.tsadok/dev   990 2019-03-26 10:16 configparser-3.7.4/setup.cfg
-rw-r--r-- israel.tsadok/dev   120 2019-03-26 10:05 configparser-3.7.4/setup.py
-rw-r--r-- israel.tsadok/dev 12559 2019-03-26 10:16 configparser-3.7.4/PKG-INFO
-rw-r--r-- israel.tsadok/dev  1050 2019-03-26 10:05 configparser-3.7.4/LICENSE
+ STATUS=0
+ [ 0 -ne 0 ]
+ cd configparser-3.7.4
+ /bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.c5mbxG
+ umask 022
+ cd /tmp/configparser/build/bdist.linux-x86_64/rpm/BUILD
+ cd configparser-3.7.4
+ python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    package_dir={'': 'src'},
  File "/tmp/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/tmp/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
    dist.parse_config_files(ignore_option_errors=True)
  File "/tmp/venv/lib/python3.6/site-packages/setuptools/dist.py", line 702, in parse_config_files
    self._parse_config_files(filenames=filenames)
  File "/tmp/venv/lib/python3.6/site-packages/setuptools/dist.py", line 599, in _parse_config_files
    (parser.read_file if six.PY3 else parser.readfp)(reader)
  File "/usr/lib/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 108: ordinal not in range(128)
error: Bad exit status from /var/tmp/rpm-tmp.c5mbxG (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.c5mbxG (%build)
error: command 'rpmbuild' failed with exit status 1
```

This happens in Python 2.7 and 3.7, with setuptools 40.8.0.

**Comment by jaraco** [comment]
Can you suggest a way I might be able to replicate this issue, perhaps with Docker?

**Comment by itsadok** [comment]
Try this as your Dockerfile:
```
FROM centos:7

RUN yum -y install git rpm-build python \
 && curl -O https://bootstrap.pypa.io/get-pip.py \
 && python get-pip.py pip==19.0.3 setuptools==40.8.0 wheel==0.33.1 \
 && git clone https://github.com/jaraco/configparser \
 && cd configparser \
 && python setup.py bdist_rpm || true
```

(I added the `|| true` in the end so that the image build succeeds, and you can run setup.py again in a container if you like)

**Comment by jaraco** [comment]
Confirmed this issue is fixed with Setuptools 41, based on this Dockerfile:

```
FROM centos:7

RUN yum -y install git rpm-build python \
 && curl -O https://bootstrap.pypa.io/get-pip.py

RUN python get-pip.py pip==19.0.3 setuptools==41.0.0 wheel==0.33.1 \
 && git clone https://github.com/jaraco/configparser

WORKDIR configparser
RUN python setup.py bdist_rpm || true
```
